# Generated by Django 4.1.7 on 2023-03-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['in_basket']},
        ),
    ]
