# Generated by Django 4.1.7 on 2023-03-12 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_task_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Item',
        ),
    ]
